platform :ios, '7.0'
pod 'JSONKit', '~> 1.5pre'
pod 'ProgressHUD', '~> 1.3'
pod 'SBJson', '~> 4.0.1'
pod 'DDPageControl', '~> 0.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'SDWebImage-ProgressView', '~> 0.3.1'
pod 'FMDB', '~> 2.3'
pod 'NSData+Base64', '~> 1.0.0'
pod 'MHCustomTabBarController', '~> 1.2.0'
pod 'MMProgressHUD', '~> 0.2.2'
pod 'IQKeyboardManager', '~> 3.0.6'
pod 'YTFPlaceholderTableView', '~> 0.2.1'
pod 'KissXML', '~> 5.0'
pod 'GDataXML-HTML', '~> 1.1.0'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'EGOTableViewPullRefreshAndLoadMore', '~> 1.0.1'

